name: Daily JSON Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run Python script
        run: python handler.py

      # Skip the git push — let GitHub Pages handle deployment
