name: Daily JSON Update

on:
  schedule:
    - cron: '0 0 * * *'  # every day at 00:00 UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run Python script
      run: python handler.py

    - name: Commit and push result
      run: |
        git config user.name "iivashch"
        git config user.email USER_EMAIL
        git add public/data.json
        git commit -m "Daily update of JSON" || echo "No changes to commit"
        git push
