name: Daily JSON Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Required to commit

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Run script
        run: python handler.py

      - name: Commit and push updated data
        run: |
          git config user.name "iivashch"
          git config user.email "${USER_EMAIL}"
          git add docs/data.json
          git commit -m "Auto-update data.json" || echo "No changes"
          git push
